---
sidebar: sidebar 
permalink: vmware/vmw-hybrid-use-cases.html 
keywords: NetApp Solutions, ehc, enterprise hybrid cloud, use case, hyperscalers, vmware 
summary:  
---
= NetApp与 VMware 混合多云的用例
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
概述在规划混合云或云优先部署时对 IT 组织重要的用例。



== 热门用例

用例包括：

* 灾难恢复，
* 在数据中心维护期间托管工作负载，* 快速爆发，需要超出本地数据中心配置的额外资源，
* VMware 站点扩展，
* 快速迁移到云端，
* 开发/测试，以及
* 利用云补充技术实现应用程序的现代化。


在本文档中，将使用 VMware 用例详细说明云工作负载参考。这些用例是：

* 保护（包括灾难恢复和备份/还原）
* 迁移
* 延长




=== IT 之旅

大多数组织都处于转型和现代化的征程中。作为此过程的一部分，公司正在尝试利用其现有的 VMware 投资，同时利用云优势并探索使迁移过程尽可能无缝的方法。由于数据已经在云端，这种方法将使他们的现代化工作变得非常容易。

对于这种情况最简单的答案是每个超大规模企业都提供 VMware 产品。与NetApp Cloud Volumes 一样，VMware 提供了一种将本地 VMware 环境移动或扩展到任何云的方法，使您能够保留现有的本地资产、技能和工具，同时在云中本地运行工作负载。这降低了风险，因为不会出现服务中断或需要更改 IP，并使 IT 团队能够使用现有技能和工具以在本地的方式进行操作。这可以加速云迁移并更顺利地过渡到混合多云架构。



=== 了解补充 NFS 存储选项的重要性

虽然任何云中的 VMware 都为每个客户提供了独特的混合功能，但有限的补充 NFS 存储选项限制了其对于存储工作负载繁重的组织的实用性。由于存储直接与主机绑定，因此扩展存储的唯一方法是添加更多主机 - 而这会使存储密集型工作负载的成本增加 35-40％ 或更多。这些工作负载只需要额外的存储空间，而不是额外的马力。但这意味着需要支付额外的主机费用。

让我们考虑一下这种情况：

一个客户只需要五台主机来提供 CPU 和内存，但是有大量的存储需求，需要 12 台主机来满足存储需求。当他们只需要增加存储空间时，这个要求最终会真正打破财务平衡，因为他们必须购买额外的马力。

当您规划云采用和迁移时，评估最佳方法并采取最简单的途径来减少总投资始终非常重要。对于任何应用程序迁移来说，最常见和最简单的方法是重新托管（也称为提升和转移），其中不需要虚拟机（VM）或数据转换。将NetApp Cloud Volumes 与 VMware 软件定义数据中心 (SDDC) 结合使用，在补充 vSAN 的同时，提供了简单的提升和转移选项。
