---
sidebar: sidebar 
permalink: vmware/vmw-hybrid-summary.html 
keywords: NetApp Solutions, hybrid, Multicloud, enterprise hybrid cloud, hyperscalers, vmware 
summary:  
---
= 总结与结论： NetApp为何选择 VMware 作为混合多云平台
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Cloud Volumes 与针对主要超大规模企业的 VMware 解决方案为希望利用混合云的组织提供了巨大的潜力。本节的其余部分提供了用例，表明集成NetApp Cloud Volumes 可以实现真正的混合多云功能。



== 用例 #1：优化存储

当使用 RVtools 输出执行大小调整练习时，马力（vCPU/vMem）比例与存储平行是显而易见的。很多时候，组织会发现他们所处的境地是，所需的存储空间使集群的规模远远超出了马力所需的范围。

通过集成NetApp Cloud Volumes，组织可以通过简单的迁移方法实现基于 vSphere 的云解决方案，无需重新平台化、无需 IP 更改、无需架构更改。此外，通过此优化，您可以扩展存储空间，同时将主机数量保持在 vSphere 所需的最少量，但不会改变存储层次结构、安全性或可用的文件。这使您可以优化部署并将总体 TCO 降低 35–45%。通过这种集成，您还可以在几秒钟内将存储从热存储扩展到生产级性能。



== 用例2：云迁移

由于多种原因，组织面临着将应用程序从本地数据中心迁移到公共云的压力：租约即将到期；财务指令要求从资本支出 (capex) 转向运营支出 (opex)；或者仅仅是自上而下的命令要求将所有内容迁移到云端。

当速度至关重要时，只有简化的迁移方法是可行的，因为重新平台化和重构应用程序以适应云的特定 IaaS 平台既缓慢又昂贵，通常需要数月时间。通过将NetApp Cloud Volumes 与用于客户机连接存储的带宽高效的SnapMirror复制（包括与应用程序一致的 Snapshot 副本和 HCX 结合的 RDM、特定于云的迁移（例如 Azure Migrate）或用于复制虚拟机的第三方产品）相结合，这种转变比依赖耗时的 I/O 过滤机制更容易。



== 用例3：数据中心扩展

当数据中心由于季节性需求高峰或仅仅是稳定的有机增长而达到容量限制时，迁移到云托管的 VMware 以及NetApp Cloud Volumes 是一个简单的解决方案。利用NetApp Cloud Volumes，可以通过提供跨可用区域的高可用性和动态扩展功能，非常轻松地创建、复制和扩展存储。利用NetApp Cloud Volumes 有助于克服对延伸集群的需求，从而最大限度地减少主机集群容量。



== 用例 #4：灾难恢复至云端

在传统方法中，如果发生灾难，复制到云中的虚拟机需要转换到云自己的虚拟机管理程序平台才能恢复 - 这不是危机期间要处理的任务。

通过使用NetApp Cloud Volumes 进行来宾连接存储，使用来自本地的SnapCenter和SnapMirror复制以及公共云虚拟化解决方案，可以设计出一种更好的灾难恢复方法，允许在完全一致的 VMware SDDC 基础架构上恢复虚拟机副本以及特定于云的恢复工具（例如 Azure Site Recovery）或等效的第三方工具（如 Veeam）。这种方法还使您能够快速执行灾难恢复演习和勒索软件恢复。通过按需添加主机，您还可以扩展到全面生产以进行测试或在灾难期间进行扩展。



== 用例 #5：应用程序现代化

应用程序进入公共云后，组织将希望利用数百种强大的云服务来实现其现代化和扩展。通过使用NetApp Cloud Volumes，现代化是一个简单的过程，因为应用程序数据不会被锁定在 vSAN 中，并且允许在包括 Kubernetes 在内的广泛用例中实现数据移动。



== 结束语

无论您的目标是全云还是混合云， NetApp Cloud Volumes 都提供了出色的选项来部署和管理应用程序工作负载以及文件服务和块协议，同时通过使数据需求无缝连接到应用程序层来降低 TCO。

无论使用情况如何，选择您最喜欢的云/超大规模器以及NetApp Cloud Volumes，以快速实现云优势、一致的基础架构和跨本地和多个云的操作、工作负载的双向可移植性以及企业级容量和性能。

它与用于连接存储的熟悉的过程和程序相同。请记住，新名称只是改变了数据的位置；工具和流程都保持不变， NetApp Cloud Volumes 有助于优化整体部署。
