---
sidebar: sidebar 
permalink: vmware/vmw-azure-avs-overview.html 
keywords: NetApp Solutions, hyperscalers, azure, avs, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= NetApp的 Azure AVS 功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
详细了解NetApp为 Azure VMware 解决方案 (AVS) 带来的功能 - 从NetApp作为来宾连接存储设备或补充 NFS 数据存储到迁移工作流、扩展/爆发到云、备份/还原和灾难恢复。

通过选择以下选项跳转到所需内容的部分：

* link:#config["在 Azure 中配置 AVS"]
* link:#datastore["NetApp的 AVS 存储选项"]
* link:#solutions["NetApp /VMware 云解决方案"]




== 在 Azure 中配置 AVS

与本地一样，规划基于云的虚拟化环境对于成功创建虚拟机和迁移的生产就绪环境至关重要。

本部分介绍如何设置和管理 Azure VMware 解决方案，并将其与用于连接NetApp存储的可用选项结合使用。


NOTE: 来宾内存储是将Cloud Volumes ONTAP连接到 Azure VMware 解决方案的唯一支持方法。

设置过程可分为以下步骤：

* 注册资源提供者并创建私有云
* 连接到新的或现有的 ExpressRoute 虚拟网络网关
* 验证网络连接并访问私有云


查看详细信息link:../vmware/vmw-azure-avs-setup.html["AVS配置步骤"]。



== NetApp的 AVS 存储选项

NetApp存储可以在 Azure AVS 中以多种方式使用 - 既可以作为猜测连接，也可以作为补充 NFS 数据存储。

请访问link:vmw-hybrid-support-configs.html["支持的NetApp存储选项"]了解更多信息。

Azure 支持以下配置的NetApp存储：

* Azure NetApp Files(ANF) 作为来宾连接存储
* Cloud Volumes ONTAP (CVO) 作为来宾连接存储
* Azure NetApp Files(ANF) 作为补充 NFS 数据存储


查看详细信息link:../vmware/vmw-azure-avs-guest-storage.html["AVS 的来宾连接存储选项"]。查看详细信息link:../vmware/vmw-azure-avs-nfs-ds-config.html["AVS 的补充 NFS 数据存储选项"]。



== 解决方案用例

借助NetApp和 VMware 云解决方案，许多用例都可以在 Azure AVS 中轻松部署。针对 VMware 定义的每个云区域都定义了这些用例：

* 保护（包括灾难恢复和备份/还原）
* 延长
* 迁移


link:vmw-azure-avs-solutions.html["浏览适用于 Azure AVS 的NetApp解决方案"]
