---
sidebar: sidebar 
permalink: google/gcp-gcnv-service-operation.html 
keywords: physical security, operations team, customer responsibilities, malicious sre protection, certifications, gdpr 
summary: Google Cloud NetApp Volumes团队管理 Google Cloud 中的后端服务，并使用多种策略来保护平台安全并防止不必要的访问。 
---
= 服务运营
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Google Cloud NetApp Volumes团队管理 Google Cloud 中的后端服务，并使用多种策略来保护平台安全并防止不必要的访问。

每个客户都有自己独特的子网，默认情况下，该子网的访问权限与其他客户隔离，并且Google Cloud NetApp Volumes中的每个租户都有自己的命名空间和 VLAN，以实现完全的数据隔离。用户通过身份验证后，服务交付引擎 (SDE) 只能读取特定于该租户的配置数据。



== 物理安全

经过适当的预先批准，只有现场工程师和带有NetApp标志的现场支持工程师 (FSE) 才能进入笼子和机架进行物理工作。不允许存储和网络管理。只有这些现场资源能够执行硬件维护任务。

对于现场工程师，将提出工作说明书 (SOW) 的票证，其中包括机架 ID 和设备位置 (RU)，所有其他详细信息都包含在票证中。对于NetApp FSE，必须向 COLO 提出现场访问票，票上应包含访客的详细信息、日期和时间，以供审计。  FSE 的 SOW 在内部传达给NetApp。



== 运营团队

Google Cloud NetApp Volumes的运营团队由Google Cloud NetApp Volumes的生产工程和站点可靠性工程师 (SRE) 以及硬件的NetApp现场支持工程师和合作伙伴组成。所有运营团队成员均已获得在 Google Cloud 工作的认证，并且每张提出的工单都会保留详细的工作记录。此外，还制定了严格的变更控制和批准流程，以确保每个决策都经过适当的审查。

SRE 团队管理控制平面以及如何将数据从 UI 请求路由到Google Cloud NetApp Volumes中的后端硬件和软件。  SRE 团队还管理系统资源，例如卷和 inode 最大值。  SRE 不得与客户数据交互或访问客户数据。  SRE 还提供与退货授权 (RMA) 的协调，例如后端硬件的新磁盘或内存更换请求。



== 客户责任

Google Cloud NetApp Volumes的客户管理其组织的 Active Directory 和用户角色管理以及卷和数据操作。客户可以拥有管理角色，并可以使用NetApp和 Google Cloud 提供的两个预定义角色（管理员和查看者）将权限委托给同一 Google Cloud 项目内的其他最终用户。

管理员可以将客户项目中的任何 VPC 与客户认为合适的Google Cloud NetApp Volumes对等连接。客户有责任管理对其 Google Cloud 市场订阅的访问以及管理有权访问数据平面的 VPC。



== 恶意 SRE 保护

可能出现的一个问题是， Google Cloud NetApp Volumes如何防范恶意 SRE 或 SRE 凭证被泄露的情况？

只有有限数量的 SRE 个人可以访问生产环境。管理权限进一步限制于少数经验丰富的管理员。 Google Cloud NetApp Volumes生产环境中任何人执行的所有操作都会被记录下来，并且我们的安全信息和事件管理 (SIEM) 威胁情报平台会检测到基线异常或可疑活动。因此，可以在对Google Cloud NetApp Volumes后端造成太大损害之前跟踪和缓解恶意行为。



== 卷生命周期

Google Cloud NetApp Volumes仅管理服务内的对象，而不是卷内的数据。只有访问卷的客户端才能管理数据、ACL、文件所有者等。这些卷中的数据在静止时是加密的，并且访问权限仅限于Google Cloud NetApp Volumes实例的租户。

Google Cloud NetApp Volumes的卷生命周期是创建-更新-删除。卷会保留卷的 Snapshot 副本，直到卷被删除，并且只有经过验证的Google Cloud NetApp Volumes管理员才能删除Google Cloud NetApp Volumes中的卷。当管理员请求删除卷时，需要额外输入卷名称来验证删除。卷被删除后，该卷将消失并且无法恢复。

如果Google Cloud NetApp Volumes合同终止， NetApp会在特定时间段后将卷标记为删除。在该时间段到期之前，您可以根据客户的要求恢复卷。



== 认证

Google Cloud NetApp Volumes for Google Cloud 目前已通过 ISO/IEC 27001:2013 和 ISO/IEC 27018:2019 标准认证。该服务最近还收到了 SOC2 Type I 认证报告。有关NetApp对数据安全和隐私的承诺，请参阅 https://www.netapp.com/company/trust-center/compliance/["合规性：数据安全和数据隐私"^]。



== GDPR

我们对隐私和 GDPR 合规性的承诺体现在我们的许多 https://www.netapp.com/how-to-buy/sales-terms-and-conditions%22%20/o%20%22SEO%20-%20Sales%20Terms%20and%20Conditions["客户合同"^]，例如我们的 https://netapp.na1.echosign.com/public/esignWidget?wid=CBFCIBAA3AAABLblqZhCqPPgcufskl_71q-FelD4DHz5EMJVOkqqT0iiORT10DlfZnZeMpDrse5W6K9LEw6o*["客户Data Processing附录"^]，其中包括 https://ec.europa.eu/info/law/law-topic/data-protection/international-dimension-data-protection/standard-contractual-clauses-scc_en["标准合同条款"^]由欧盟委员会提供。我们还在我们的隐私政策中做出了这些承诺，并以我们公司行为准则中规定的核心价值观为后盾。
