---
sidebar: sidebar 
permalink: videos/hmc-aws-videos.html 
summary: 展示NetApp的 AWS 混合多云解决方案的视频和演示 
keywords: hybrid cloud, rosa, fsx ontap, azure vmware, netapp hci, videos, demos 
---
= 观看有关使用NetApp的 Amazon Web Services 混合多云解决方案的视频
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
探索 NetApp 的综合视频库，其中包含NetApp针对 AWS 的混合多云解决方案。观看有关 VMware Cloud on AWS 和Amazon FSx for ONTAP的客户机连接存储、TCO 节省、补充数据存储和迁移工作流程的视频，包括 Windows 和 Linux 场景。



== 来宾连接存储

.使用 iSCSI 的 Windows 客户机连接存储与 FSx ONTAP
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.使用 NFS 连接 Linux 客户机和 FSx ONTAP 的存储
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]


== TCO 和补充数据存储

.VMware Cloud on AWS 使用Amazon FSx ONTAP节省 TCO
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.VMware Cloud on AWS 补充数据存储（带有Amazon FSx ONTAP）
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]


== 迁移工作流程 (HCX)

.VMC 的 VMware HCX 部署和配置设置
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.使用 VMware HCX for VMC 和 FSx ONTAP进行 vMotion 迁移演示
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.使用 VMware HCX for VMC 和 FSx ONTAP进行冷迁移演示
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]